# wrangler.toml (wrangler v3.78.6^)
name = "sub-scraping"
main = "./.output/server/index.mjs"
tsconfig = "./tsconfig.json"
route = { pattern = "/search*", custom_domain = true }
compatibility_date = "2024-12-24"

minify = true

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "pnpm build:cloudflare"
watch_dir = "./.output/server"
